packages:
  - docs
  - examples/**
  - packages/**

allowBuilds:
  esbuild: true
  sharp: true # for nextra-theme-docs
  unrs-resolver: true # for nextra-theme-docs

catalog:
  tsdown: "^0.x"
  typescript: "npm:@typescript/typescript6@^6.0.2"
  typescript-7: "npm:typescript@^7.0.2"

linkWorkspacePackages: true

packageExtensions:
  # react-error-boundary is missing @types/react in its dependencies.
  # This causes pnpm's strict symlinking to evaluate its types to `any`, leading to JSX errors.
  # Injecting it here forces pnpm to provide the types.
  "react-error-boundary@*":
    peerDependencies:
      "@types/react": "^19.0.0"
