/**
 * Strict type equality check. Evaluates to true if X and Y are exactly the same type.
 * This is a famous TypeScript community hack discovered by Matt McCutchen.
 *
 * @example
 * type A = IsEqual<string, string>; // true
 * type B = IsEqual<string, string | undefined>; // false
 * type C = IsEqual<any, unknown>; // false
 *
 * @see https://github.com/microsoft/TypeScript/issues/27024#issuecomment-421529650
 */
export type IsEqual<X, Y> =
  (<T>() => T extends X ? 1 : 2) extends <T>() => T extends Y ? 1 : 2
    ? true
    : false;

/**
 * Automatically extracts keys from a base type `U` that were NOT overridden by an extending type `T`.
 * Useful when you want to group inherited properties (like HTML attributes) but keep explicitly overridden ones.
 *
 * @example
 * type Native = { id: string; children: ReactNode };
 * type Custom = { id: string; children: CustomRenderer };
 *
 * // 'id' matches exactly, but 'children' was overridden with a different type!
 * type Keys = ExtractExactKeys<Custom, Native>; // "id"
 */
export type ExtractExactKeys<T, U> = {
  [K in keyof U]: K extends keyof T
    ? IsEqual<T[K], U[K]> extends true
      ? K
      : never
    : never;
}[keyof U];

/**
 * Creates a union of object types where exactly one key from the provided union `K` is `true`,
 * and all other keys from `K` are `false`.
 *
 * This is useful for creating mutually exclusive boolean flags.
 *
 * @example
 * type ExclusiveFlags = ExactlyOneTrue<"isSmall" | "isMedium" | "isLarge">;
 * // Evaluates to:
 * // | { isSmall: true; isMedium: false; isLarge: false }
 * // | { isSmall: false; isMedium: true; isLarge: false }
 * // | { isSmall: false; isMedium: false; isLarge: true }
 */
export type ExactlyOneTrue<K extends PropertyKey> = {
  [P in K]: {
    [Q in K]: Q extends P ? true : false;
  };
}[K];

/**
 * Extracts a variant from a union type where the given key `K` is explicitly `true`.
 * Designed to work smoothly with discriminated unions generated by `ExactlyOneTrue`.
 *
 * @example
 * type ExclusiveFlags = ExactlyOneTrue<"isSmall" | "isLarge">;
 * type SmallVariant = ExtractTrueVariant<ExclusiveFlags, "isSmall">; // { isSmall: true, isLarge: false }
 */
export type ExtractTrueVariant<T, K extends keyof T> = Extract<
  T,
  Record<K, true>
>;
