import { GridError } from "#errors.ts";
import type { GridDataReadonly } from "#schema.ts";

import {
  ensureArray,
  isString,
  isUJSONObject,
  type UJSONObject,
  type UJSONValue,
} from "@jsoc/utils";

/**
 * Property in a {@link GridRow}. It can also be referred to as a column key.
 */
export type RowProperty = Extract<keyof UJSONObject, string>;
/**
 * Value of a property in a {@link GridRow}.
 * - It can be one of the JSON value types (array, boolean, null, number, object, string)
 *   or `undefined`.
 * - `undefined` is added to support inconsistent json structures which may have missing
 *   properties in some rows. Example:
 * ```json
 * [
 *  {"a": 1, "b": 2, "c": 2},
 *  {"a": 1, "c": 3}
 * ]
 * ```
 * In this case, `b` is `undefined` in the second row.
 */
export type RowPropertyValue = UJSONValue;
/**
 * Single row. A row is a plain object (property-value pairs).
 * Refer {@link generateRows} for how rows are derived from {@link GridDataReadonly}.
 */
export type GridRow = UJSONObject;
/**
 * Collection of {@link GridRow}s generated by {@link generateRows}.
 */
export type GridRows = Array<GridRow>;
/**
 * Unique value of a {@link RowProperty} in all {@link GridRows}. This value must be a string or
 * number so grid components that expect a primitive id can work reliably.
 */
export type GridRowId = Extract<RowPropertyValue, string | number>;

/**
 * Generates {@link GridRows} from the provided {@link GridDataReadonly}.
 * @throws a {@link GridError} if the `data` cannot be normalized.
 */
export function generateRows(data: GridDataReadonly): GridRows {
  const dataArray = normalizeData(data);
  const validRows: GridRow[] = [];
  const invalidRows: unknown[] = [];

  for (const row of dataArray) {
    if (isUJSONObject(row)) {
      validRows.push(row);
    } else {
      invalidRows.push(row);
    }
  }

  if (invalidRows.length) {
    console.warn(
      `Found ${invalidRows.length} invalid rows in provided data. The rows will be ignored.`,
      invalidRows,
    );
  }

  return validRows;
}

/**
 * Normalizes the grid data into an array of objects
 */
function normalizeData(data: GridDataReadonly): unknown[] {
  let unknownData: unknown;

  try {
    if (isString(data)) {
      unknownData = JSON.parse(data) as unknown;
    } else {
      unknownData = structuredClone(data);
    }
  } catch (e) {
    throw new GridError("Error occured while normalizing grid data.", e);
  }

  return ensureArray(unknownData);
}
