import { GridError } from "#errors.ts";
import type { GridDataReadonly } from "#schema.ts";

import {
  ensureArray,
  isArrayOfObjects,
  isConcreteObject,
  isPlainObject,
  isString,
  type JSONValue,
  type PlainObject,
} from "@jsoc/utils";

/**
 * Property in a {@link GridRow}. It can also be referred to as a column key.
 */
export type RowProperty = string;
/**
 * Value of a property in a {@link GridRow}.
 * - It can be one of the JSON value types (array, boolean, null, number, object, string)
 *   or undefined.
 */
export type RowPropertyValue = JSONValue | undefined;
/**
 * Single row. A row is a plain object (property-value pairs).
 * Refer {@link generateRows} for how rows are derived from {@link GridDataReadonly}.
 */
export type GridRow = Record<RowProperty, RowPropertyValue>;
/**
 * Collection of {@link GridRow}s generated by {@link generateRows}.
 */
export type GridRows = Array<GridRow>;
/**
 * Unique value of a {@link RowProperty} in all {@link GridRows}. This value must be a string or
 * number so grid components that expect a primitive id can work reliably.
 */
export type GridRowId = Extract<RowPropertyValue, string | number>;

/**
 * Generates {@link GridRows} from the provided {@link GridDataReadonly}.
 * @throws a {@link GridError} if the payload cannot be parsed or validated.
 */
export function generateRows(data: GridDataReadonly): GridRows {
  const dataNormalized = normalizeGridData(data);
  const rows = ensureArray(dataNormalized).filter(isGridRow);

  return rows;
}

/**
 * Normalizes the grid data into a plain object or array of objects, cloning to avoid
 * mutations and parsing strings as JSON.
 */
function normalizeGridData(
  data: GridDataReadonly,
): PlainObject | PlainObject[] {
  let normalizedData;

  if (isString(data)) {
    try {
      normalizedData = JSON.parse(data) as unknown;
    } catch (e) {
      throw new GridError("Provided JSON is not valid.", e);
    }
  } else {
    try {
      // stringify first so we fail fast on unsupported JSON values (functions/classes) before structuredClone
      JSON.stringify(data);
      // data is ensured to be JSON object or array of JSON objects,
      // now we can deep clone to prevent modification of the original data
      normalizedData = structuredClone(data);
    } catch (e) {
      throw new GridError("Provided grid data is not valid.", e);
    }
  }

  assertIsValidGridData(normalizedData);

  return normalizedData;
}

/**
 * Throws {@link GridError} if the argument is not a JSON object or array of JSON objects.
 * This is a building block for {@link generateRows}.
 */
export function assertIsValidGridData(
  arg: unknown,
): asserts arg is PlainObject | PlainObject[] {
  if (!isPlainObject(arg) && !isArrayOfObjects(arg)) {
    throw new GridError(
      "Provided grid data is not valid.",
      "Provided grid data is neither a JSON object nor an array of JSON objects.",
    );
  }
}

/**
 * Type guard that confirms the provided object is a {@link GridRow} by checking every property value.
 */
function isGridRow(row: unknown): row is GridRow {
  if (!isPlainObject(row) || !isConcreteObject(row)) {
    return false;
  }

  return Object.values(row).every(isRowPropertyValue);
}

/**
 * Recursively validates a value against {@link RowPropertyValue}.
 */
function isRowPropertyValue(value: unknown): value is RowPropertyValue {
  if (
    value === undefined ||
    value === null ||
    typeof value === "boolean" ||
    typeof value === "number" ||
    typeof value === "string"
  ) {
    return true;
  }

  if (Array.isArray(value)) {
    return value.every(isRowPropertyValue);
  }

  if (isPlainObject(value)) {
    return Object.values(value).every(isRowPropertyValue);
  }

  return false;
}
